export const modules = [
  { key: '/category', base: '/api/category', title: '分类', columns: [{ dataIndex: 'id' }, { dataIndex: 'name', title: '名称' }, { dataIndex: 'sort', title: '排序' }], fields: [{ name: 'name', label: '分类名' }, { name: 'sort', label: '排序', type: 'number' }, { name: 'keyword', label: '关键词' }] },
  { key: '/box', base: '/api/box', title: '盒子', columns: [{ dataIndex: 'id' }, { dataIndex: 'title', title: '标题' }, { dataIndex: 'video', title: '视频URL' }], fields: [{ name: 'title', label: '标题' }, { name: 'video', label: '视频URL' }, { name: 'thumb', label: '封面' }] },
  { key: '/group', base: '/api/group', title: '分组', columns: [{ dataIndex: 'id' }, { dataIndex: 'name', title: '名称' }, { dataIndex: 'rule', title: '权限' }], fields: [{ name: 'name', label: '名称' }, { name: 'rule', label: '权限(菜单串)', textarea: true }] },
  { key: '/template', base: '/api/template', title: '落地模板', columns: [{ dataIndex: 'id' }, { dataIndex: 'model', title: '标识' }, { dataIndex: 'title', title: '标题' }, { dataIndex: 'thumb', title: '封面' }], fields: [{ name: 'model', label: 'model' }, { name: 'title', label: '标题' }, { name: 'info', label: '描述' }, { name: 'thumb', label: '封面' }] },
  { key: '/payTemplate', base: '/api/payTemplate', title: '支付模板', columns: [{ dataIndex: 'id' }, { dataIndex: 'model', title: '标识' }, { dataIndex: 'title', title: '标题' }], fields: [{ name: 'model', label: 'model' }, { name: 'title', label: '标题' }, { name: 'thumb', label: '封面' }] },
  { key: '/short', base: '/api/short', title: '短链', columns: [{ dataIndex: 'id' }, { dataIndex: 'name', title: '名称' }, { dataIndex: 'model', title: 'model' }, { dataIndex: 'key', title: 'key' }], fields: [{ name: 'name', label: '名称' }, { name: 'model', label: 'model' }, { name: 'key', label: 'key' }, { name: 'sort', label: '排序', type: 'number' }] },
  { key: '/domain', base: '/api/domain', title: '域名', columns: [{ dataIndex: 'id' }, { dataIndex: 'host', title: '域名' }, { dataIndex: 'type', title: '类型' }], fields: [{ name: 'host', label: '域名' }, { name: 'type', label: '类型', type: 'number' }, { name: 'agent', label: '代理', type: 'number' }] },
  { key: '/notice', base: '/api/notice', title: '公告', columns: [{ dataIndex: 'id' }, { dataIndex: 'title', title: '标题' }], fields: [{ name: 'title', label: '标题' }, { name: 'content', label: '内容', textarea: true }] },
  { key: '/order', base: '/api/order', title: '订单', columns: [{ dataIndex: 'id' }, { dataIndex: 'orderId', title: '订单号' }, { dataIndex: 'video', title: '视频' }, { dataIndex: 'price', title: '金额' }, { dataIndex: 'status', title: '状态' }], fields: [] },
  { key: '/pay', base: '/api/pay', title: '支付', columns: [{ dataIndex: 'id' }, { dataIndex: 'name', title: '支付名' }, { dataIndex: 'model', title: 'model' }, { dataIndex: 'switch', title: '开关' }], fields: [{ name: 'name', label: '平台名称' }, { name: 'model', label: 'model' }, { name: 'payId', label: '商户id' }, { name: 'payKey', label: '商户key' }, { name: 'payGateway', label: '网关' }, { name: 'extraMoney', label: '奸商加费', type: 'number' }] },
  { key: '/code', base: '/api/code', title: '卡密', columns: [{ dataIndex: 'id' }, { dataIndex: 'content', title: '卡密' }, { dataIndex: 'status', title: '状态' }], fields: [{ name: 'content', label: '卡密内容' }, { name: 'agent', label: '代理id', type: 'number' }] },
  { key: '/kl', base: '/api/kl', title: '卡链', columns: [{ dataIndex: 'id' }, { dataIndex: 'agent', title: '代理' }, { dataIndex: 'kl', title: '倒数值' }], fields: [{ name: 'agent', label: '代理id', type: 'number' }, { name: 'kl', label: '倒数值', type: 'number' }, { name: 'init', label: '初始值', type: 'number' }] },
  { key: '/kllist', base: '/api/kllist', title: '卡密明细', columns: [{ dataIndex: 'id' }, { dataIndex: 'orderId', title: '订单号' }, { dataIndex: 'price', title: '扣量金额' }], fields: [] },
  { key: '/tx', base: '/api/tixian', title: '提现', columns: [{ dataIndex: 'id' }, { dataIndex: 'agent', title: '代理' }, { dataIndex: 'price', title: '金额' }, { dataIndex: 'status', title: '状态' }], fields: [] },
  { key: '/tousu', base: '/api/tousu', title: '投诉', columns: [{ dataIndex: 'id' }, { dataIndex: 'ip', title: 'ip' }, { dataIndex: 'content', title: '内容' }], fields: [] },
  { key: '/checkLog', base: '/api/checkLog', title: '检测日志', columns: [{ dataIndex: 'id' }, { dataIndex: 'url', title: 'url' }, { dataIndex: 'response', title: '返回' }], fields: [] }
];
