server {
  listen 80;
  server_name wanli.jiekebao.top;
  client_max_body_size 128m;

  location /c/ {
    alias /opt/wanli-v2/static/c/;
    index index.html;
    try_files $uri $uri/ /c/index.html;
  }
  location /admin/ {
    alias /opt/wanli-v2/static/admin/;
    index index.html;
    try_files $uri $uri/ /admin/index.html;
  }
  location / {
    proxy_pass http://127.0.0.1:9501;
  }
}

server {
  listen 443 ssl;
  server_name wanli.jiekebao.top;
  ssl_certificate /etc/ssl/private/wanli.crt;
  ssl_certificate_key /etc/ssl/private/wanli.key;
  client_max_body_size 128m;

  location /c/ {
    alias /opt/wanli-v2/static/c/;
    index index.html;
    try_files $uri $uri/ /c/index.html;
  }
  location /admin/ {
    alias /opt/wanli-v2/static/admin/;
    index index.html;
    try_files $uri $uri/ /admin/index.html;
  }
  location / {
    proxy_pass http://127.0.0.1:9501;
  }
}
