CREATE DATABASE IF NOT EXISTS wl DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'wl'@'localhost' IDENTIFIED BY 'wl';
GRANT ALL PRIVILEGES ON wl.* TO 'wl'@'localhost';
FLUSH PRIVILEGES;
